In [7]:
#Importing Required Libraries 
import pandas as pd

#Loading the CSV File
df = pd.read_csv('concisedfile.csv')

#Renaming Columns to get them ready for the loop 
df = df.rename(columns={'Course': 'Course.0', 'End Date': 'End Date.0'})

#Creating a new filtered DataFrame with the specified column names.
filtered_df = pd.DataFrame(columns=['Name','Course', 'End Date'])

#Looping the huge CSV file and sorting it by courses, student names, and the semester with specified end date 2023-11
for i in range(24):  
    a = df[['Name', f'Course.{i}', f'End Date.{i}']] 
    a.drop(0, axis = 0, inplace=True)
    result=(a[a[f'End Date.{i}'] == '2023-11'])
    result = result.rename(columns={f'Course.{i}': 'Course', f'End Date.{i}': 'End Date'})
    filtered_df = filtered_df.append(result, ignore_index=True)

#Sort Values by the Course Column and set it to the index to simply indexing
filtered_df.sort_values(['Course'], ascending=True,inplace=True)
filtered_df.set_index('Course', inplace=True)
filtered_df
#Can be used to filter out a specific course with the specified end date or semester
#filtered_df.loc['ESLEO'].head(20)

                Name End Date
Course
AVI4M       Ziyi Tan  2023-11
AVI4M        Keyu Lu  2023-11
AVI4M       Kexin Wu  2023-11
AVI4M    Chenyan Gan  2023-11
AVI4M     Herui Peng  2023-11
...              ...      ...
SCH3U     Herui Peng  2023-11
SCH3U     Yixuan Ren  2023-11
SCH3U   Jiawei Huang  2023-11
SCH3U       Kerui He  2023-11
SCH3U    Wenyue Pang  2023-11

[167 rows x 2 columns]